name: CI - Protocols

on:
  pull_request:
    paths:
      - 'svc/nullblock-protocols/**'
      - 'lib/**'
      - '.github/workflows/rust-service.yml'
      - '.github/task-definitions/nullblock-protocols.json'
  push:
    branches: [main]
    paths:
      - 'svc/nullblock-protocols/**'
      - 'lib/**'
      - '.github/workflows/rust-service.yml'
      - '.github/task-definitions/nullblock-protocols.json'

jobs:
  ci:
    uses: ./.github/workflows/rust-service.yml
    with:
      service-name: nullblock-protocols
      service-path: svc/nullblock-protocols
      service-port: 8001
      ecs-service: nullblock-protocols
      run-deploy: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    secrets: inherit
