name: Check Hecate PR

on:
  pull_request:
    branches: [ prod ]
    types: [ synchronize ]

env:
  NODE_VERSION: 18.19.0
  SERVICE_PATH: svc/hecate

jobs:
  check:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}-check-pr
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - name: Check for changes in service directory
        id: check-changes
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^${{ env.SERVICE_PATH }}/'
          then
            echo "::set-output name=service_changed::true"
          else
            echo "::set-output name=service_changed::false"
          fi

      - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
        if: steps.check-changes.outputs.service_changed == 'true'

      - uses: actions/setup-node@v4
        if: steps.check-changes.outputs.service_changed == 'true'
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: ${{ env.SERVICE_PATH }}/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.SERVICE_PATH }}
        if: steps.check-changes.outputs.service_changed == 'true'

      - name: Check eslint
        run: npm run lint:check
        working-directory: ${{ env.SERVICE_PATH }}
        if: steps.check-changes.outputs.service_changed == 'true'

      - name: Typescript check
        run: npm run ts:check
        working-directory: ${{ env.SERVICE_PATH }}
        if: steps.check-changes.outputs.service_changed == 'true'

      - name: Stylelint check
        run: npm run style:check
        working-directory: ${{ env.SERVICE_PATH }}
        if: steps.check-changes.outputs.service_changed == 'true'

      - name: Build check
        run: npm run build -- --throw-warnings
        working-directory: ${{ env.SERVICE_PATH }}
        if: steps.check-changes.outputs.service_changed == 'true'

      - name: Commit lint PR title
        run: echo "${{ github.event.pull_request.title }}" | npx --no-install commitlint -g commitlint.config.js
        working-directory: ${{ env.SERVICE_PATH }}
        if: steps.check-changes.outputs.service_changed == 'true'

