name: Release Hecate

on:
  push:
    branches: [ prod ] 

jobs:
  build:
    uses: ./.github/workflows/ssr-boost-build.yml
    with:
      app-build-args: --unlock-robots
      service-path: svc/hecate

  release:
    needs: [build]
    uses: ./.github/workflows/ssr-boost-release.yml
    with:
      has-release-asset: true
      service-path: svc/hecate
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  # inject actual version to app (only demo)
  inject-version:
    needs: [release]
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}-inject-version
      cancel-in-progress: true

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: svc/hecate

      - name: Inject version
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: '"APP_VERSION"'
          replace: '"${{ needs.release.outputs.version }}"'
          regex: false

      - name: App build
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: ${{ github.workspace }}
          overwrite: true

  docker-build:
    needs: [release, inject-version]
    uses: ./.github/workflows/ssr-boost-docker-build.yml
    with:
      registry: ghcr.io
      image-name: ${{ github.repository }}/hecate
      version: ${{ needs.release.outputs.version }}
      app-build-path: build/
      service-path: svc/hecate
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  deploy-aws:
    needs: [docker-build]
    uses: ./.github/workflows/ssr-boost-deploy-aws.yml
    with:
      image: ${{ needs.docker-build.outputs.image-tag }}
      service: Hecate
      cluster: DevCluster
      task-container-name: hecate
      service-path: svc/hecate
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

