name: release app

on:
  push:
    branches: [ prod ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: svc/hecate
    uses: lomray-software/vite-ssr-boost/.github/workflows/ssr-boost-build.yml@prod
    with:
      app-build-args: --unlock-robots

  release:
    needs: [build]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: subdirectory/path
    uses: lomray-software/vite-ssr-boost/.github/workflows/ssr-boost-release.yml@prod
    with:
      has-release-asset: true
    secrets:
      github-token: ${{ secrets.github_token }}

  inject-version:
    needs: [release]
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}-inject-version
      cancel-in-progress: true
    defaults:
      run:
        working-directory: subdirectory/path
    steps:
      - uses: actions/download-artifact@v5
        with:
          name: build-artifact

      - name: inject version
        uses: jacobtomlinson/gha-find-replace@v4
        with:
          find: '"app_version"'
          replace: '"${{ needs.release.outputs.version }}"'
          regex: false

      - name: app build
        uses: actions/upload-artifact@v5
        with:
          name: build-artifact
          path: ${{ github.workspace }}
          overwrite: true

  docker-build:
    needs: [release, inject-version]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: subdirectory/path
    uses: lomray-software/vite-ssr-boost/.github/workflows/ssr-boost-docker-build.yml@prod
    with:
      registry: ghcr.io
      image-name: ${{ github.repository }}/web
      version: ${{ needs.release.outputs.version }}
      app-build-path: ./build
    secrets:
      github-token: ${{ secrets.github_token }}

  deploy-aws:
    needs: [docker-build]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: subdirectory/path
    uses: lomray-software/vite-ssr-boost/.github/workflows/ssr-boost-deploy-aws.yml@prod
    with:
      image: ${{ needs.docker-build.outputs.image-tag }}
      service: snakebytes
      cluster: devcluster
      task-container-name: web
    secrets:
      aws_access_key_id: ${{ secrets.aws_access_key_id }}
      aws_secret_access_key: ${{ secrets.aws_secret_access_key }}
      aws_region: ${{ secrets.aws_region }}

