name: SSR BOOST Release

on:
  workflow_call:
    inputs:
      build-folder:
        required: false
        type: string
        default: build
      has-release-asset:
        required: false
        type: boolean
        default: false 
      service-path:
        required: true
        type: string
        default: svc/hecate
    secrets:
      github-token:
        required: true
    outputs:
      version:
        description: "New package version"
        value: ${{ jobsbs.release.outputs.version }}

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}-release
      cancel-in-progress: true
    outputs:
      version: ${{ steps.package-version.outputs.version }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: build-artifact

      - name: Create release asset
        if: ${{ inputs.has-release-asset }}
        run: |
          cd ${{ inputs.service-path }}
          zip -r build.zip ${{ inputs.build-folder }} package.json package-lock.json README.md
        
      - name: Install dependencies
        run: |
          cd ${{ inputs.service-path }}
          npm ci

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}
        run: |
          cd ${{ inputs.service-path }}
          npx semantic-release

      - name: Get version
        id: package-version
        run: |
          cd ${{ inputs.service-path }}
          npx @lomray/microservices-cli package-version
